---
# When changing options in this file, please also run:
#    python3 script/generate.py edge
# to update the edge addon config (beta/stable configs will be updated on next release by release script)
base: &base
  url: https://github.com/matchlighter/typedaemon
  description: Typescript-based Automations, Services, and Entities

  panel_icon: mdi:graph

  init: false
  homeassistant: 2021.3.0

  arch:
  - amd64
  - armhf
  - armv7
  # - aarch64
  # - i386

  ingress: true
  ingress_port: 0
  ingress_stream: true
  host_network: false
  ports:
    80/tcp: 1980
    9000/tcp: 9000
  ports_description:
    80/tcp: Web interface
    9000/tcp: Http interface/API

  hassio_api: false
  homeassistant_api: true
  auth_api: true

  uart: false

  map:
  - config:rw
  - media:rw
  - share:rw

  services:
  - mqtt:want

  environment:
    TYPEDAEMON_CONFIG: /config/typedaemon

  options: {}
  schema: {}

typedaemon-edge:
  <<: *base
  directory: typedaemon-edge
  name: TypeDaemon (edge)
  version: 'edge'
  slug: typedaemon-edge
  description: "Development version of TypeDaemon add-on"
  stage: experimental
  advanced: true
  image: ghcr.io/matchlighter/typedaemon
  base_image: ghcr.io/matchlighter/typedaemon:edge
  options:
    home_assistant_dashboard_integration: false

typedaemon-beta:
  <<: *base
  directory: typedaemon-beta
  name: TypeDaemon (beta)
  version: '0.3.0'  # BETA
  slug: typedaemon-beta
  description: "Beta version of TypeDaemon add-on"
  image: ghcr.io/matchlighter/typedaemon
  stage: experimental
  advanced: true
  options:
    home_assistant_dashboard_integration: false

typedaemon-stable:
  <<: *base
  directory: typedaemon
  name: TypeDaemon
  version: '0.3.0'  # STABLE
  slug: typedaemon
  image: ghcr.io/matchlighter/typedaemon

copy_files:
  - DOCS.md
  # - icon.png
  # - logo.png
  - README.md
  - translations/en.yaml
