---
url: https://github.com/matchlighter/typedaemon
description: Beta version of TypeDaemon add-on
panel_icon: mdi:graph
init: false
homeassistant: 2021.3.0
arch:
- amd64
- armhf
- armv7
ingress: true
ingress_port: 0
ingress_stream: true
host_network: false
ports:
  80/tcp: 1980
  9000/tcp: 9000
ports_description:
  80/tcp: Web interface
  9000/tcp: Http interface/API
hassio_api: false
homeassistant_api: true
auth_api: true
uart: false
map:
- config:rw
- media:rw
- share:rw
services:
- mqtt:want
environment:
  TYPEDAEMON_CONFIG: /config/typedaemon
options:
  home_assistant_dashboard_integration: false
schema: {}
name: TypeDaemon (beta)
version: 0.3.6
slug: typedaemon-beta
image: ghcr.io/matchlighter/typedaemon
stage: experimental
advanced: true
