name: TypeDaemon Edge
version: dev
slug: typedaemon-edge
description: Typescript-based Automations, Services, and Entities
url: https://github.com/matchlighter/typedaemon
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:graph
init: false
homeassistant: 2021.3.0
arch:
- aarch64
- amd64
# - armhf
- armv7
# - i386
ports:
  80/tcp: 1880
  9000/tcp: 9000
ports_description:
  80/tcp: Web interface
  9000/tcp: Http interface/API
hassio_api: true
homeassistant_api: true
host_network: true
auth_api: true
uart: false
map:
- config:rw
- media:rw
- share:rw

services:
- mqtt:want

environment:
  TYPEDAEMON_CONFIG: /config/typedaemon

options: {}
schema: {}

stage: experimental
advanced: true

image: ghcr.io/matchlighter/typedaemon
